### **Importing Libraries and Dataset**

In [21]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import pyarrow.csv as pv
import pyarrow.parquet as pq

In [3]:
# Importing the October 2019 dataset
data1 = pv.read_csv('2019-Oct.csv')

In [4]:
# Sending the data from pyarrow to pandas dataframe
data1_p = data1.to_pandas()

In [5]:
# Fetching first 5 rows of the dataset 2019 October
data1_p.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [6]:
# Importing the November 2019 dataset
data2 = pv.read_csv('2019-Nov.csv')

In [7]:
# sending the data from pyarrow to pandas dataframe
data2_p = data2.to_pandas()

In [8]:
# Fetching first 5 rows of the dataset 2019 November
data2_p.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866035,appliances.sewing_machine,janome,293.65,530496790,8e5f4f83-366c-4f70-860e-ca7417414283
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810775923,appliances.kitchen.washer,lg,712.87,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
4,2019-11-01 00:00:01 UTC,view,1004775,2053013555631882655,electronics.smartphone,xiaomi,183.27,558856683,313628f1-68b8-460d-84f6-cec7a8796ef2

In [9]:
# Merging the two datasets
df = pd.concat([data1_p, data2_p], axis=0)

In [10]:
# Getting the shape of the merged dataset
df.shape

(109950743, 9)

In [11]:
# Fetching first 5 rows of the merged dataset
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [12]:
# Checking the memory usage of the dataframe
df.memory_usage(deep=True).sort_values(ascending=False)

user_session     9345812723
event_time       7916453496
category_code    7057952705
brand            5950574936
event_type       5834028531
Index             879605944
product_id        879605944
category_id       879605944
price             879605944
user_id           879605944
dtype: int64

In [ ]:
# Dropping the user_session column as it is not required for analysis
df = df.drop(columns=['user_session'])

In [14]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,,shiseido,35.79,541312140
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,,543.10,519107250
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217

In [15]:
# Convert Object type columns to category type to reduce memory usage
df['event_type']= df['event_type'].astype('category')
df['brand']=df['brand'].astype('category')
df['category_code']=df['category_code'].astype('category')

In [16]:
# Converting the 'event_time' column to datetime format
df['event_time'] = pd.to_datetime(df['event_time'])

In [17]:
# Downcasting the numerical columns to reduce memory usage
df['product_id'] = df['product_id'].astype('int32')
df['category_id'] = df['category_id'].astype('int32')
df['user_id'] = df['user_id'].astype('int32')
df['price'] = df['price'].astype('float32')

In [18]:
# Extracting year, month and day from the 'event_time' column
df['year'] = df['event_time'].dt.year
df['month'] = df['event_time'].dt.month
df['day'] = df['event_time'].dt.day

In [20]:
# Checking for null values in the dataset
df.isnull().sum()

event_time       0
event_type       0
product_id       0
category_id      0
category_code    0
brand            0
price            0
user_id          0
year             0
month            0
day              0
dtype: int64

In [23]:
# Saving the cleaned and feature engineered dataset in parquet format with zstd compression
df.to_parquet(
    "final_compressed.parquet",
    index=False,
    compression="zstd"
)